name: photos_repository
description: repository that manages the photo domain
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  image_compositor:
    path: ../image_compositor

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
